Update layout.html
halo-dev/theme-earth pull request #104
Opened 2023-08-31 09:13 UTC by Dacong-wu

增加移除 sidebar 组件的功能
问题背景：当我在开发 photos 页面的时候，发现根本无法移除 sidebar 导致这片区域形成了浪费

2023-08-31 09:14 UTC, Dacong-wu commented
/assign @johnniang

2023-09-01 06:51 UTC, ruibaby requested changes

2023-09-01 06:51 UTC, ruibaby commented on templates/modules/layout.html
> +      <div class="z-0 col-span-4" th:classappend="${sidebar == 'remove'} ? '':'sm:col-span-3'">
我建议如果某些页面完全不需要 sidebar，那应该使用一个新的变量比如 `showSidebar` 来控制，避免使用一个 remove 的魔法值。

2023-09-04 13:38 UTC, Dacong-wu commented
OK

2023-09-17 14:39 UTC, closed without merging