feat: update share-modal.html with dark mode styles
halo-dev/theme-earth pull request #127
Opened 2023-11-26 02:43 UTC by Anyexyz

```release-note
优化暗色模式下的分享弹窗样式。
```

2023-11-27 03:50 UTC, ruibaby commented
标题建议在暗色模式下显示为亮色：

<img width="818" alt="图片" src="https://github.com/halo-dev/theme-earth/assets/21301288/fb1de235-3d45-4489-8ef8-ea86fef5cc3f">

关闭按钮建议在鼠标悬浮的时候也是亮色系：
<img width="696" alt="图片" src="https://github.com/halo-dev/theme-earth/assets/21301288/5a0a6b3b-81a5-420a-a0fb-99757a38e47d">

分享按钮在鼠标悬浮的时候建议有反馈：

<img width="639" alt="图片" src="https://github.com/halo-dev/theme-earth/assets/21301288/5d1b3a16-fb8e-4bd8-ba25-0b0303af96e6">

2023-11-28 07:01 UTC, Anyexyz commented
修改了

2023-11-28 12:52 UTC, ruibaby requested changes

2023-11-28 12:52 UTC, ruibaby commented on templates/modules/hero.html
> +          <span class="text-sm font-light text-white opacity-100" th:text="${site.subtitle}"></span>
一个 PR 内不要包含不同的修改。

2023-11-28 13:24 UTC, ruibaby approved these changes
/lgtm

2023-11-28 13:25 UTC, merged