refactor: redirect to current url after login
halo-dev/theme-earth pull request #189
Opened 2024-10-12 07:48 UTC by wan92hen

登录后 redirect_uri 改为当前所在路径

2024-10-12 07:57 UTC, ruibaby requested changes

2024-10-12 07:57 UTC, ruibaby commented on templates/modules/header.html
> +                  href="/login"
try:

```suggestion
                  th:href="|/login?redirect_uri=${#ctx.getExchange().getRequest().getPathWithinApplication()}|"
```

2024-10-12 08:31 UTC, wan92hen commented on templates/modules/header.html
> +                  href="/login"
这个没有包含 query 参数

2024-10-14 04:01 UTC, merged

2024-10-14 07:24 UTC, JohnNiang commented on templates/modules/header.html
> +                  href="/login"
这里好像可以通过 `ctx.getExchange().getRequest().getURI()` 获取，但是不会包含 fragment。