fix: header image display bug
halo-dev/theme-earth pull request #52
Opened 2023-02-17 18:27 UTC by jdgjxxchy

2023-02-20 13:39 UTC, ruibaby requested changes

2023-02-20 13:39 UTC, ruibaby commented on templates/modules/header.html
> +          <img th:if="${not #strings.isEmpty(site.logo)}" th:src="${site.logo}" th:alt="Logo" class="h-full w-8" />
我认为这里应该改为 `w-auto`，因为我们无法知道使用者 Logo 的具体尺寸。

2023-02-20 13:41 UTC, jdgjxxchy commented on templates/modules/header.html
> +          <img th:if="${not #strings.isEmpty(site.logo)}" th:src="${site.logo}" th:alt="Logo" class="h-full w-8" />
其实是页面本身w-6 h-6

2023-02-20 13:47 UTC, ruibaby approved these changes
/approve

2023-02-21 02:11 UTC, JohnNiang approved these changes
/lgtm

Thanks for your first contribution!

2023-02-21 02:12 UTC, merged