feat: add filters to the cover image
halo-dev/theme-earth pull request #89
Opened 2023-06-30 08:20 UTC by LIlGG

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
为封面图增加一个暗色调滤镜，解决在亮色调背景图的情况下标题无法看清的问题。

#### Which issue(s) this PR fixes:
Fixes #86 

#### Does this PR introduce a user-facing change?

```release-note
为封面图增加暗色调滤镜
```

2023-06-30 08:27 UTC, ruibaby reviewed
<img width="1589" alt="image" src="https://github.com/halo-dev/theme-earth/assets/21301288/81b603ae-7056-42b7-9672-a1479803baee">

/lgtm

This is amazing!!!!

2023-06-30 08:33 UTC, wan92hen commented
awesome

2023-07-03 03:25 UTC, JohnNiang requested changes

2023-07-03 03:25 UTC, JohnNiang commented on pnpm-lock.yaml
建议使用 6.0 的 pnpm。

2023-07-03 03:25 UTC, JohnNiang commented on templates/post.html
> +      class="sticky top-20 z-[5] w-full cursor-pointer rounded-xl bg-white p-3 shadow transition-all duration-500 hover:shadow-md dark:bg-slate-800"
建议 revert 无关的修改。

2023-07-03 03:39 UTC, LIlGG commented on templates/post.html
> +      class="sticky top-20 z-[5] w-full cursor-pointer rounded-xl bg-white p-3 shadow transition-all duration-500 hover:shadow-md dark:bg-slate-800"
使用 [Prettier](https://prettier.io/) 之后会自动格式化代码。

2023-07-03 03:39 UTC, LIlGG commented on pnpm-lock.yaml
已修改

2023-07-03 07:03 UTC, JohnNiang commented
需要先解决一下冲突。

2023-07-03 07:19 UTC, ruibaby reviewed
/lgtm

2023-07-03 07:20 UTC, LIlGG commented
> 需要先解决一下冲突。

已解决。

2023-07-07 02:29 UTC, ruibaby approved these changes

2023-07-07 02:30 UTC, merged