feat:增加底部公安联网备案信息及对应设置
halo-dev/theme-earth pull request #97
Opened 2023-07-18 08:55 UTC by fan4w

### 修改内容
在 #6  基础上加入了公安联网备案相关的设置项
不输入公安联网备案号时不渲染公安备案图标
### 效果图
#### 底部
![image](https://github.com/halo-dev/theme-earth/assets/127591077/0e21d753-5085-4f58-a935-a38b37b11f28)
#### 设置页面
![image](https://github.com/halo-dev/theme-earth/assets/127591077/d25a82e0-6662-489f-97ab-22780c872cc3)

2023-07-18 09:19 UTC, fan4w commented
抱歉...不太熟悉Github操作，没有加标签。代码也是优先考虑把功能实现，可能十分不规范...
欢迎大佬斧正，如果我写的实在太糟糕的话关掉这个pr也行 : )

2023-07-18 09:29 UTC, ruibaby requested changes
感谢贡献，以下是一些改进建议。

2023-07-18 09:29 UTC, ruibaby commented on templates/modules/footer.html
> +    <style>
直接使用 tailwindcss 的 class 即可。

如：`class="flex items-center justify-center gap-1"`

2023-07-18 09:29 UTC, ruibaby commented on templates/modules/footer.html
> +        src="/themes/theme-earth/assets/images/gongan_beian.png">
这里写死可能不太好，我们在内部封装了 assets 的调用，可以参考：https://docs.halo.run/developer-guide/theme/static-resources

```suggestion
        th:src="@{/assets/images/gongan_beian.png}">
```

2023-07-18 09:29 UTC, ruibaby commented on templates/modules/footer.html
> +  <span class="container mx-auto block text-center text-sm text-gray-500 dark:text-slate-300">
这里是否需要判断一下是否填写了备案号？如果没有设置，下面的代码应该都不需要有。

2023-07-18 09:30 UTC, ruibaby commented
> 抱歉...不太熟悉Github操作，没有加标签。代码也是优先考虑把功能实现，可能十分不规范... 欢迎大佬斧正，如果我写的实在太糟糕的话关掉这个pr也行 : )

没关系，我们非常鼓励大家参与开源贡献，有什么问题我们可以进行讨论。

2023-07-19 10:04 UTC, ruibaby approved these changes
/lgtm

感谢贡献！

2023-07-19 10:06 UTC, merged